apiVersion: v1
description: A Helm chart for Gatekeeper
name: gatekeeper-operator
keywords:
  - open policy agent
version: v3.1.0-beta.4
home: https://github.com/open-policy-agent/gatekeeper
sources:
  - https://github.com/open-policy-agent/gatekeeper.git
appVersion: v3.1.0-beta.4
