unrestricted_licenses:
  - Apache-2.0
  - CC-BY-3.0
  - ISC
  - AFL-2.1
  - AFL-3.0
  - Artistic-1.0
  - Artistic-2.0
  - Apache-1.1
  - BSD-1-Clause
  - BSD-2-Clause
  - BSD-3-Clause
  - 0BSD
  - FTL
  - LPL-1.02
  - MS-PL
  - MIT
  - NCSA
  - OpenSSL
  - PHP-3.0
  - TCP-wrappers
  - W3C
  - Xnet
  - Zlib

reciprocal_licenses:
  - CC0-1.0
  - APSL-2.0
  - CDDL-1.0
  - CDDL-1.1
  - CPL-1.0
  - EPL-1.0
  - IPL-1.0
  - MPL-1.0
  - MPL-1.1
  - MPL-2.0
  - MPL-2.0-no-copyleft-exception
  - Ruby

restricted_licenses:
  - GPL-1.0-only
  - GPL-1.0-or-later
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-3.0-only
  - GPL-3.0-or-later
  - LGPL-2.0-only
  - LGPL-2.0-or-later
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - NPL-1.0
  - NPL-1.1
  - OSL-1.0
  - OSL-1.1
  - OSL-2.0
  - OSL-2.1
  - OSL-3.0
  - QPL-1.0
  - Sleepycat

allowlisted_modules:
  # MIT: https://github.com/ghodss/yaml/blob/master/LICENSE
  - github.com/ghodss/yaml
  # BSD: https://github.com/gogo/protobuf/blob/master/LICENSE
  - github.com/gogo/protobuf

  # Apache 2.0
  - github.com/spf13/cobra

  # https://github.com/xeipuuv/gojsonpointer/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonpointer
  # https://github.com/xeipuuv/gojsonreference/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonreference

  # MIT: https://github.com/kubernetes-sigs/yaml/blob/master/LICENSE
  - sigs.k8s.io/yaml

  # BSD-2-Clause-FreeBSD
  - github.com/rcrowley/go-metrics
