---
{{- if not .Values.disableAudit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "gatekeeper.commonLabels" . | nindent 4 }}
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    control-plane: audit-controller
    gatekeeper.sh/operation: audit
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-audit
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: '{{ template "gatekeeper.name" . }}'
      chart: '{{ template "gatekeeper.name" . }}'
      control-plane: audit-controller
      gatekeeper.sh/operation: audit
      gatekeeper.sh/system: "yes"
      heritage: '{{ .Release.Service }}'
      release: '{{ .Release.Name }}'
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | trim | nindent 8 }}
        {{- end }}
        {{- if .Values.auditPodAnnotations }}
        {{- toYaml .Values.auditPodAnnotations | trim | nindent 8 }}
        {{- end }}
      labels:
        {{- include "gatekeeper.podLabels" . | nindent 8 }}
        {{- include "audit.podLabels" . | nindent 8 }}
        {{- include "gatekeeper.commonLabels" . | nindent 8 }}
        app: '{{ template "gatekeeper.name" . }}'
        chart: '{{ template "gatekeeper.name" . }}'
        control-plane: audit-controller
        gatekeeper.sh/operation: audit
        gatekeeper.sh/system: "yes"
        heritage: '{{ .Release.Service }}'
        release: '{{ .Release.Name }}'
    spec:
      affinity:
        {{- toYaml .Values.audit.affinity | nindent 8 }}
      automountServiceAccountToken: true
      containers:
      - {{- if .Values.image.release }}
        image: {{ .Values.image.repository }}:{{ .Values.image.release }}
        {{- else }}
        image: {{ .Values.image.repository }}
        {{- end }}
        args:
        - --audit-interval={{ .Values.auditInterval }}
        - --log-level={{ (.Values.audit.logLevel | empty | not) | ternary .Values.audit.logLevel .Values.logLevel }}
        - --constraint-violations-limit={{ .Values.constraintViolationsLimit }}
        - --validating-webhook-configuration-name={{ .Values.validatingWebhookName }}
        - --mutating-webhook-configuration-name={{ .Values.mutatingWebhookName }}
        - --audit-from-cache={{ .Values.auditFromCache }}
        {{ if hasKey .Values "auditChunkSize" }}- --audit-chunk-size={{ .Values.auditChunkSize }}{{- end }}
        - --audit-match-kind-only={{ .Values.auditMatchKindOnly }}
        {{ if hasKey .Values "emitAuditEvents" }}- --emit-audit-events={{ .Values.emitAuditEvents }}{{- end }}
        {{ if hasKey .Values "logStatsAudit" }}- --log-stats-audit={{ .Values.logStatsAudit }}{{- end }}
        - --audit-events-involved-namespace={{ .Values.auditEventsInvolvedNamespace }}
        - --operation=audit
        - --operation=status
        - --operation=generate
        {{ if hasKey .Values "enableViolationExport" }}
        - --enable-violation-export={{ .Values.enableViolationExport }}
        {{- end }}
        {{ if hasKey .Values.audit "connection" }}
        - --audit-connection={{ .Values.audit.connection }}
        {{- end }}
        {{ if hasKey .Values.audit "channel" }}
        - --audit-channel={{ .Values.audit.channel }}
        {{- end }}
        {{ if not .Values.disableMutation}}- --operation=mutation-status{{- end }}
        - --logtostderr
        - --health-addr=:{{ .Values.audit.healthPort }}
        - --prometheus-port={{ .Values.audit.metricsPort }}
        - --enable-external-data={{ .Values.enableExternalData }}
        - --enable-generator-resource-expansion={{ .Values.enableGeneratorResourceExpansion }}
        
        {{- range .Values.metricsBackends}}
        - --metrics-backend={{ . }}
        {{- end }}
        
        {{- if .Values.audit.logFile}}
        - --log-file={{ .Values.audit.logFile }}
        {{- end }}
        - --disable-cert-rotation={{ or .Values.audit.disableCertRotation .Values.externalCertInjection.enabled }}
        - --external-data-provider-response-cache-ttl={{ .Values.externaldataProviderResponseCacheTTL }}
        - --enable-k8s-native-validation={{ .Values.enableK8sNativeValidation }}
        
        {{- if hasKey .Values "defaultCreateVAPForTemplates"}}
        - --default-create-vap-for-templates={{ .Values.defaultCreateVAPForTemplates }}
        {{- end }}
        
        {{- if hasKey .Values "defaultCreateVAPBindingForConstraints"}}
        - --default-create-vap-binding-for-constraints={{ .Values.defaultCreateVAPBindingForConstraints }}
        {{- end }}
        {{ if hasKey .Values "defaultWaitForVAPBGeneration"}}
        - --default-wait-for-vapb-generation={{ .Values.defaultWaitForVAPBGeneration }}
        {{- end }}
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: manager
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE),k8s.container.name=$(CONTAINER_NAME)
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.audit.healthPort }}
          timeoutSeconds: {{ .Values.audit.livenessTimeout }}
        name: '{{ .Values.audit.containerName }}'
        ports:
        - containerPort: {{ .Values.audit.metricsPort }}
          name: metrics
          protocol: TCP
        - containerPort: {{ .Values.audit.healthPort }}
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.audit.healthPort }}
          timeoutSeconds: {{ .Values.audit.readinessTimeout }}
        resources:
          {{- toYaml .Values.audit.resources | nindent 10 }}
        securityContext:
          {{- if .Values.enableRuntimeDefaultSeccompProfile }}
          seccompProfile:
            type: RuntimeDefault
          {{- end }}
          {{- toYaml .Values.audit.securityContext | nindent 10}}
        volumeMounts:
        - mountPath: /certs
          name: cert
          readOnly: true
        - mountPath: /tmp/audit
          name: tmp-volume
      dnsPolicy: {{ .Values.audit.dnsPolicy }}
      hostNetwork: {{ .Values.audit.hostNetwork }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.audit.nodeSelector | nindent 8 }}
      {{- if .Values.audit.priorityClassName }}
      priorityClassName:  {{ .Values.audit.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.audit.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ .Values.audit.serviceAccount.name }}
      terminationGracePeriodSeconds: 60
      tolerations:
        {{- toYaml .Values.audit.tolerations | nindent 8 }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: gatekeeper-webhook-server-cert
      {{- if .Values.audit.writeToRAMDisk }}
      - emptyDir:
          medium: Memory
      {{ else }}
      - emptyDir: {}
      {{- end }}
        name: tmp-volume
{{- end }}
