---
{{- if not .Values.disableMutation }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations: {{- toYaml .Values.mutatingWebhookAnnotations | trim | nindent 4 }}
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ .Values.mutatingWebhookName }}'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.mutatingWebhookURL }}
    url: https://{{ .Values.mutatingWebhookURL }}/v1/mutate
    {{- else }}
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/mutate
    {{- end }}
  failurePolicy: {{ .Values.mutatingWebhookFailurePolicy }}
  {{- if .Values.mutatingWebhookMatchConditions }}
  {{- if ge (int .Capabilities.KubeVersion.Minor) 28 }}
  matchConditions: {{ toYaml .Values.mutatingWebhookMatchConditions | nindent 4 }}
  {{- end }}
  {{- end }}
  matchPolicy: Exact
  name: mutation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - {{ .Release.Namespace }}
    
    {{- range $key, $value := .Values.mutatingWebhookExemptNamespacesLabels}}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- range $value }}
      - {{ . }}
      {{- end }}
    {{- end }}
  objectSelector: {{ toYaml .Values.mutatingWebhookObjectSelector | nindent 4 }}
  reinvocationPolicy: {{ .Values.mutatingWebhookReinvocationPolicy }}
  rules:
  {{- if .Values.mutatingWebhookCustomRules }}
  {{- toYaml .Values.mutatingWebhookCustomRules | nindent 2 }}
  {{- else }}
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    - pods/ephemeralcontainers
    - pods/exec
    - pods/log
    - pods/eviction
    - pods/portforward
    - pods/proxy
    - pods/attach
    - pods/binding
    - deployments/scale
    - replicasets/scale
    - statefulsets/scale
    - replicationcontrollers/scale
    - services/proxy
    - nodes/proxy
    - services/status
  {{- end }}
  sideEffects: None
  timeoutSeconds: {{ .Values.mutatingWebhookTimeoutSeconds }}
{{- end }}
