resources:
- role.yaml
- role_binding.yaml
- service_account.yaml
- podsecuritypolicy.yaml
# - leader_election_role.yaml
# - leader_election_role_binding.yaml
# Comment the following 3 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
# - auth_proxy_service.yaml
# - auth_proxy_role.yaml
# - auth_proxy_role_binding.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: manager-role
  path: webhook_permissions_patch.yaml
