---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-webhook-service
  namespace: '{{ .Release.Namespace }}'
spec:
  
  ports:
  - name: https-webhook-server
    port: 443
    targetPort: webhook-server
{{- if .Values.service }}
{{- if .Values.service.healthzPort }}
  - name: http-webhook-healthz
    port: {{ .Values.service.healthzPort }}
    targetPort: healthz
      {{- end }}
  {{- end }}
  {{- if .Values.service }}
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
    {{- end }}
  {{- end }}
  selector:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    control-plane: controller-manager
    gatekeeper.sh/operation: webhook
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
