---
{{- if not .Values.disableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations: {{- toYaml .Values.validatingWebhookAnnotations | trim | nindent 4 }}
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ .Values.validatingWebhookName }}'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.validatingWebhookURL }}
    url: https://{{ .Values.validatingWebhookURL }}/v1/admit
    {{- else }}
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/admit
    {{- end }}
  failurePolicy: {{ .Values.validatingWebhookFailurePolicy }}
  {{- if .Values.validatingWebhookMatchConditions }}
  {{- if ge (int .Capabilities.KubeVersion.Minor) 28 }}
  matchConditions: {{ toYaml .Values.validatingWebhookMatchConditions | nindent 4 }}
  {{- end }}
  {{- end }}
  matchPolicy: Exact
  name: validation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
    
    {{- /* 1. Get mandatory exemption from helper */ -}}
    {{- $defaults := include "gatekeeper.mandatoryNamespaceExemption" . | fromYaml -}}
    {{- /* 2. Merge user values with mandatory exemption. */ -}}
    {{- $merged := merge (deepCopy .Values.validatingWebhookExemptNamespacesLabels) $defaults -}}
    {{- range $key, $value := $merged }}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- /* Ensure current namespace is in the list for the metadata key */ -}}
      {{- $list := $value -}}
      {{- if eq $key "kubernetes.io/metadata.name" }}
        {{- $list = append $value $.Release.Namespace | uniq -}}
      {{- end }}
      {{- range $list }}
      - {{ . }}
      {{- end }}
    {{- end }}
  objectSelector: {{ toYaml .Values.validatingWebhookObjectSelector | nindent 4 }}
  rules:
  {{- if .Values.validatingWebhookCustomRules }}
  {{- toYaml .Values.validatingWebhookCustomRules | nindent 2 }}
  {{- else }}
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    {{- if .Values.enableDeleteOperations }}
    - DELETE
    {{- end }}
    {{- if .Values.enableConnectOperations }}
    - CONNECT
    {{- end }}
    resources:
    - '*'
    # Explicitly list all known subresources except "status" (to avoid destabilizing the cluster and increasing load on gatekeeper).
    # You can find a rough list of subresources by doing a case-sensitive search in the Kubernetes codebase for 'Subresource("'
    {{- range .Values.validatingWebhookSubResources }}
    - {{ . }}
    {{- end }}
    scope: '{{ .Values.validatingWebhookScope }}'
  {{- end }}
  sideEffects: None
  timeoutSeconds: {{ .Values.validatingWebhookTimeoutSeconds }}
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/admitlabel
  failurePolicy: {{ .Values.validatingWebhookCheckIgnoreFailurePolicy }}
  matchPolicy: Exact
  name: check-ignore-label.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    
    {{- /* 1. Get mandatory exemption from helper */ -}}
    {{- $defaults := include "gatekeeper.mandatoryNamespaceExemption" . | fromYaml -}}
    {{- /* 2. Merge user values with mandatory exemption. */ -}}
    {{- $merged := merge (deepCopy .Values.validatingWebhookExemptNamespacesLabels) $defaults -}}
    {{- range $key, $value := $merged }}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- /* Ensure current namespace is in the list for the metadata key */ -}}
      {{- $list := $value -}}
      {{- if eq $key "kubernetes.io/metadata.name" }}
        {{- $list = append $value $.Release.Namespace | uniq -}}
      {{- end }}
      {{- range $list }}
      - {{ . }}
      {{- end }}
    {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
    scope: '*'
  sideEffects: None
  timeoutSeconds: {{ .Values.validatingWebhookTimeoutSeconds }}
{{- end }}
