# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/config.gatekeeper.sh_configs.yaml
- bases/syncset.gatekeeper.sh_syncsets.yaml
- bases/status.gatekeeper.sh_constraintpodstatuses.yaml
- bases/status.gatekeeper.sh_constrainttemplatepodstatuses.yaml
- bases/status.gatekeeper.sh_mutatorpodstatuses.yaml
- bases/status.gatekeeper.sh_expansiontemplatepodstatuses.yaml
- bases/status.gatekeeper.sh_configpodstatuses.yaml
- bases/mutations.gatekeeper.sh_assign.yaml
- bases/mutations.gatekeeper.sh_assignimage.yaml
- bases/mutations.gatekeeper.sh_assignmetadata.yaml
- bases/mutations.gatekeeper.sh_modifyset.yaml
- bases/expansion.gatekeeper.sh_expansiontemplate.yaml
- bases/status.gatekeeper.sh_connectionpodstatuses.yaml
- bases/status.gatekeeper.sh_providerpodstatuses.yaml
- bases/connection.gatekeeper.sh_connections.yaml
- bases/constrainttemplate-customresourcedefinition.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  path: patches/preserve_unknown_fields_false.yaml

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: assign.mutations.gatekeeper.sh
  path: patches/max_name_size.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: assignmetadata.mutations.gatekeeper.sh
  path: patches/max_name_size.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: modifyset.mutations.gatekeeper.sh
  path: patches/max_name_size.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: assignimage.mutations.gatekeeper.sh
  path: patches/max_name_size.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: expansiontemplate.expansion.gatekeeper.sh
  path: patches/max_name_size.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: syncsets.syncset.gatekeeper.sh
  path: patches/max_name_size.yaml

patchesStrategicMerge:
#- patches/max_name_size_for_modifyset.yaml
#- patches/max_name_size_for_assign.yaml
#- patches/max_name_size_for_assignmetadata.yaml
#- patches/max_name_size_for_assignimage.yaml
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_configs.yaml
#- patches/webhook_in_constraintpodstatuses.yaml
#- patches/webhook_in_constrainttemplatepodstatuses.yaml
#- patches/webhook_in_assignmetadata.yaml
#- patches/webhook_in_assign.yaml
#- patches/webhook_in_connections.yaml
#- patches/webhook_in_connectionpodstatuses.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_configs.yaml
#- patches/cainjection_in_constraintpodstatuses.yaml
#- patches/cainjection_in_constrainttemplatepodstatuses.yaml
#- patches/cainjection_in_assignmetadata.yaml
#- patches/cainjection_in_assign.yaml
#- patches/cainjection_in_connections.yaml
#- patches/cainjection_in_connectionpodstatuses.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
