name: license-lint
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"

permissions:
  contents: read

jobs:
  license-lint:
    name: "license-lint"
    runs-on: oracle-vm-2cpu-8gb-x86-64
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25"
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v3.5.2

      - name: license-lint
        run: |
          export GOPATH="$HOME/go"
          PATH="$GOPATH/bin:$PATH"
          ./third_party/k8s.io/kubernetes/hack/verify-licenses.sh
