name: license-lint
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"

permissions:
  contents: read

jobs:
  license-lint:
    name: "license-lint"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "1.23"
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.5.2

      - name: license-lint
        run: |
          export GOPATH="$HOME/go"
          PATH="$GOPATH/bin:$PATH"
          ./third_party/k8s.io/kubernetes/hack/verify-licenses.sh
