name: license-lint
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"

permissions:
  contents: read

jobs:
  license-lint:
    name: "license-lint"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: "1.22"
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v3.5.2

      - name: license-lint
        run: |
          export GOPATH="$HOME/go"
          PATH="$GOPATH/bin:$PATH"
          ./third_party/k8s.io/kubernetes/hack/verify-licenses.sh
