name: license-lint
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "vendor/**"
      - "third_party/k8s.io/kubernetes/hack/verify-licenses.sh"

permissions:
  contents: read

jobs:
  license-lint:
    name: "license-lint"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25"
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3.5.2

      - name: license-lint
        run: |
          export GOPATH="$HOME/go"
          PATH="$GOPATH/bin:$PATH"
          ./third_party/k8s.io/kubernetes/hack/verify-licenses.sh
