name: release-sample-images
on:
  push:
    tags:
      - 'v*'

env:
  FAKE_READER_IMAGE_REPO: ghcr.io/open-policy-agent/fake-reader
  FAKE_SUBSCRIBER_IMAGE_REPO: ghcr.io/open-policy-agent/fake-subscriber

permissions: read-all

jobs:
  publish-sample-images:
    name: "Publish Sample Images"
    runs-on: oracle-vm-8cpu-32gb-x86-64
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'open-policy-agent/gatekeeper'
    timeout-minutes: 30
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Get tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish fake-reader image
        run: |
          if ! docker manifest inspect ${{ env.FAKE_READER_IMAGE_REPO }}:${TAG} > /dev/null 2>&1
          then
            make docker-buildx-fake-reader-release \
              VERSION=${TAG} \
              PLATFORM="linux/amd64,linux/arm64" \
              OUTPUT_TYPE=type=registry \
              GENERATE_ATTESTATIONS=true
          fi

      - name: Publish fake-subscriber image
        run: |
          if ! docker manifest inspect ${{ env.FAKE_SUBSCRIBER_IMAGE_REPO }}:${TAG} > /dev/null 2>&1
          then
            make docker-buildx-fake-subscriber-release \
              VERSION=${TAG} \
              PLATFORM="linux/amd64,linux/arm64" \
              OUTPUT_TYPE=type=registry \
              GENERATE_ATTESTATIONS=true
          fi
